project:
  type: website

website:
  title: "web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog\index.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



