project:
  type: website

website:
  title: "Brian Tarran writes..."
  description: Personal homepage of Brian Tarran
  site-url: https://brtarran.github.io/
  repo-url: https://github.com/brtarran/brtarran.github.io
  search: true
  open-graph: true
  twitter-card:
    creator: "@brtarran"

  navbar:
    left:
      - href: index.qmd
        text: 'about'
      - href: books/index.qmd
        text: 'books'
      - href: film-and-tv/index.qmd
        text: 'film & TV'
      - href: games/index.qmd
        text: 'games'
      - href: blog/index.qmd
        text: '& other stuff'
    right:
      - href: https://github.com/brtarran
        icon: github
      - href: https://twitter.com/brtarran
        icon: twitter
      - href: https://mastodon.social/@brtarran
        icon: mastodon
      - href: https://www.linkedin.com/in/brian-tarran-58b0261/
        icon: linkedin

format:
  html:
    theme: [sketchy, custom.scss]
    # css: styles.css
    toc: true

execute: 
  freeze: auto