project:
  type: website

website:
  title: "Fatso Jetson writes..."
  navbar:
    left:
      - href: about.qmd
        text: 'about'
      - href: books\index.qmd
        text: 'books'
      - href: film_&_tv\index.qmd
        text: 'film & TV'
      - href: games\index.qmd
        text: 'games'
      - href: blog\index.qmd
        text: '& other stuff'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



