---
pagetitle: Brian Tarran writes...
toc: false
webr:
  channel-type: "post-message"
  show-startup-message: false
filters:
  - webr
---

I'm **Brian Tarran**. By day, I am a **writer** and **editor** with 20 years' experience covering the research and data space. I have worked for the [Royal Statistical Society](https://rss.org.uk/) (RSS) for the past 8 years, and was editor of [Significance Magazine](https://www.significancemagazine.com/) (a joint publication of the RSS, the American Statistical Association and the Statistical Society of Australia) prior to the launch of [**Real World Data Science**](https://realworlddatascience.net/), a new data science site published by the RSS. 

I am a former editor of [Research-Live.com](https://www.research-live.com/) and was launch editor of [Impact magazine](https://www.research-live.com/sections/impact), both published by the [Market Research Society](https://www.mrs.org.uk/).

In my spare time, I'm learning how to speak and read Japanese, and I play as many games and watch as much film and TV as grown-up responsibilities allow. I plan to use this site mostly to keep track of the things I'm [playing](games/index.qmd), [watching](film-and-tv/index.qmd) and [reading](books/index.qmd), and to share what I think about them. I'm also learning how to code, so this is my space to experiment without the worry of breaking anything important!

Does this work?

```{webr-r}
fit = lm(mpg ~ am, data = mtcars)
summary(fit)
```

This is change 1

This is change 2