on:
  workflow_dispath:
  push:
    branches: main
  pull_request:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
    steps:
      - name: Check out repository
        uses: actions/checkout@v3 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          # tinytex: true 
          # uncomment below and fill to pin a version
          version: pre-release
          
      # - name: Setup Python
      #   uses: actions/setup-python@v4.1.0
            
      # add software dependencies here
      
      # - name: Install python dependencies
      #   run: |
      #     python -m pip install jupyter
      #     python -m pip install numpy
      #     python -m pip install matplotlib

      - name: Render with Quarto
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: _site